# Automatically generated by Pynguin.
import cloud_ips.network as module0


def test_case_0():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False


def test_case_1():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False


def test_case_2():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = module0.is_cloud_v0(var2)
    assert var4 is False


def test_case_3():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = module0.is_cloud_v0(var4)
    assert var6 is False
    var7 = module0.is_cloud_v0(var4)
    assert var7 is False


def test_case_4():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "N"
    var7 = module0.is_cloud_v0(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = module0.is_cloud_v0(var8)
    assert var10 is False
    var11 = module0.is_cloud_v0(var8)
    assert var11 is False
    var12 = "N"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = None
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = module0.is_cloud_v0(var14)
    assert var16 is False
    var17 = module0.is_cloud(var2)
    assert var17 is False


def test_case_5():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = module0.is_cloud_v0(var4)
    assert var6 is False
    var7 = module0.is_cloud_v0(var4)
    assert var7 is False
    var8 = "N"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = module0.is_cloud_v0(var10)
    assert var12 is False
    var13 = "N"
    var14 = module0.is_cloud_v0(var13)
    assert var14 is False
    var15 = None
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = "3L!3*@37:a"
    var18 = module0.is_cloud(var17)
    assert var18 is False


def test_case_6():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = module0.is_cloud_v0(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud_v0(var5)
    assert var6 is False


def test_case_7():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = module0.is_cloud(var0)
    assert var2 is False


def test_case_8():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = module0.is_cloud_v0(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud_v0(var5)
    assert var6 is False
    var7 = "N"
    var8 = module0.is_cloud_v0(var7)
    assert var8 is False
    var9 = None
    var10 = module0.is_cloud(var9)
    assert var10 is False
    var11 = module0.is_cloud_v0(var9)
    assert var11 is False
    var12 = None
    var13 = module0.is_cloud(var12)
    assert var13 is False
    var14 = "N"
    var15 = module0.is_cloud_v0(var14)
    assert var15 is False
    var16 = None
    var17 = module0.is_cloud(var16)
    assert var17 is False
    var18 = module0.is_cloud_v0(var16)
    assert var18 is False
    var19 = module0.is_cloud_v0(var16)
    assert var19 is False
    var20 = "N"
    var21 = module0.is_cloud_v0(var20)
    assert var21 is False
    var22 = None
    var23 = module0.is_cloud(var22)
    assert var23 is False


def test_case_9():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "3.5.136.0/22"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False


def test_case_10():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = module0.is_cloud(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = "3.5.136.0/22"
    var8 = module0.is_cloud_v0(var7)
    assert var8 is False
    var9 = module0.is_cloud_v0(var2)
    assert var9 is False


def test_case_11():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = module0.is_cloud(var0)
    assert var2 is False
    var3 = None
    var4 = module0.is_cloud(var3)
    assert var4 is False
    var5 = module0.is_cloud(var3)
    assert var5 is False


def test_case_12():
    var0 = "S|_1g{`:j[Nl#U6"
    var1 = module0.is_cloud(var0)
    assert var1 is False


def test_case_13():
    var0 = "S|_1g{`:j[Nl#U6"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = module0.is_cloud(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = module0.is_cloud(var5)
    assert var7 is False
    var8 = "N"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = module0.is_cloud_v0(var10)
    assert var12 is False
    var13 = "N"
    var14 = module0.is_cloud_v0(var13)
    assert var14 is False
    var15 = None
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = module0.is_cloud_v0(var15)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud_v0(var18)
    assert var19 is False
    var20 = "kW"
    var21 = module0.is_cloud_v0(var20)
    assert var21 is False


def test_case_14():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = module0.is_cloud(var0)
    assert var2 is False
    var3 = None
    var4 = module0.is_cloud(var3)
    assert var4 is False
    var5 = module0.is_cloud(var3)
    assert var5 is False
    var6 = "N"
    var7 = module0.is_cloud_v0(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = module0.is_cloud_v0(var8)
    assert var10 is False
    var11 = None
    var12 = module0.is_cloud_v0(var11)
    assert var12 is False
    var13 = "N"
    var14 = module0.is_cloud_v0(var13)
    assert var14 is False
    var15 = None
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = module0.is_cloud_v0(var15)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud(var18)
    assert var19 is False
    var20 = None
    var21 = module0.is_cloud(var20)
    assert var21 is False
    var22 = "3.5.136.0/22"
    var23 = module0.is_cloud_v0(var22)
    assert var23 is False
    var24 = "S|_1g{`:j[Nl#U6"
    var25 = module0.is_cloud(var24)
    assert var25 is False
    var26 = None
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = "N"
    var29 = module0.is_cloud_v0(var28)
    assert var29 is False
    var30 = None
    var31 = module0.is_cloud(var30)
    assert var31 is False
    var32 = module0.is_cloud_v0(var30)
    assert var32 is False
    var33 = module0.is_cloud_v0(var30)
    assert var33 is False
    var34 = "N"
    var35 = module0.is_cloud_v0(var34)
    assert var35 is False
    var36 = module0.is_cloud(var34)
    assert var36 is False
    var37 = None
    var38 = module0.is_cloud(var37)
    assert var38 is False


def test_case_15():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = module0.is_cloud_v0(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud_v0(var5)
    assert var6 is False
    var7 = "S|_1g{`:j[Nl#U6"
    var8 = module0.is_cloud(var7)
    assert var8 is False
    var9 = "N"
    var10 = module0.is_cloud_v0(var9)
    assert var10 is False
    var11 = None
    var12 = module0.is_cloud(var11)
    assert var12 is False
    var13 = module0.is_cloud_v0(var11)
    assert var13 is False
    var14 = "N"
    var15 = module0.is_cloud_v0(var14)
    assert var15 is False
    var16 = module0.is_cloud(var14)
    assert var16 is False
    var17 = None
    var18 = module0.is_cloud(var17)
    assert var18 is False
    var19 = module0.is_cloud(var17)
    assert var19 is False
    var20 = None
    var21 = module0.is_cloud(var20)
    assert var21 is False
    var22 = "3.5.136.0/22"
    var23 = module0.is_cloud_v0(var22)
    assert var23 is False
    var24 = "N"
    var25 = module0.is_cloud_v0(var24)
    assert var25 is False
    var26 = None
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = "N"
    var29 = module0.is_cloud_v0(var28)
    assert var29 is False
    var30 = None
    var31 = module0.is_cloud(var30)
    assert var31 is False
    var32 = module0.is_cloud_v0(var30)
    assert var32 is False
    var33 = module0.is_cloud_v0(var30)
    assert var33 is False
    var34 = "wLG@_ex6^unU7uV4f\tL"
    var35 = module0.is_cloud_v0(var34)
    assert var35 is False


def test_case_16():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False


def test_case_17():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False


def test_case_18():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "N"
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False
    var6 = module0.is_cloud(var4)
    assert var6 is False
    var7 = None
    var8 = module0.is_cloud(var7)
    assert var8 is False
    var9 = module0.is_cloud(var7)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = "3.5.136.0/22"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = "S|_1g{`:j[Nl#U6"
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = "N"
    var17 = module0.is_cloud_v0(var16)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud(var18)
    assert var19 is False
    var20 = module0.is_cloud_v0(var18)
    assert var20 is False
    var21 = "N"
    var22 = module0.is_cloud_v0(var21)
    assert var22 is False
    var23 = module0.is_cloud(var21)
    assert var23 is False
    var24 = "N"
    var25 = module0.is_cloud_v0(var24)
    assert var25 is False
    var26 = None
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = module0.is_cloud_v0(var26)
    assert var28 is False
    var29 = None
    var30 = module0.is_cloud_v0(var29)
    assert var30 is False
    var31 = module0.is_cloud_v0(var21)
    assert var31 is False


def test_case_19():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "104.198.64.0/20"
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "l3OZ\t2L4\t!"
    var7 = module0.is_cloud(var6)
    assert var7 is False


def test_case_20():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "104.198.64.0/20"
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "l3OZ\t2L4\t!"
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = "N"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = module0.is_cloud(var8)
    assert var10 is False
    var11 = None
    var12 = module0.is_cloud(var11)
    assert var12 is False
    var13 = module0.is_cloud(var11)
    assert var13 is False
    var14 = "N"
    var15 = module0.is_cloud_v0(var14)
    assert var15 is False
    var16 = None
    var17 = module0.is_cloud(var16)
    assert var17 is False
    var18 = module0.is_cloud_v0(var16)
    assert var18 is False
    var19 = None
    var20 = module0.is_cloud_v0(var19)
    assert var20 is False
    var21 = "N"
    var22 = module0.is_cloud_v0(var21)
    assert var22 is False
    var23 = module0.is_cloud(var21)
    assert var23 is False
    var24 = "N"
    var25 = module0.is_cloud_v0(var24)
    assert var25 is False
    var26 = None
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = None
    var29 = module0.is_cloud(var28)
    assert var29 is False
    var30 = "3.5.136.0/22"
    var31 = module0.is_cloud_v0(var30)
    assert var31 is False
    var32 = None
    var33 = module0.is_cloud(var32)
    assert var33 is False
    var34 = "N"
    var35 = module0.is_cloud_v0(var34)
    assert var35 is False
    var36 = None
    var37 = module0.is_cloud(var36)
    assert var37 is False
    var38 = module0.is_cloud_v0(var36)
    assert var38 is False
    var39 = module0.is_cloud_v0(var36)
    assert var39 is False
    var40 = "N"
    var41 = module0.is_cloud_v0(var40)
    assert var41 is False
    var42 = None
    var43 = module0.is_cloud(var42)
    assert var43 is False
    var44 = module0.is_cloud_v0(var42)
    assert var44 is False
    var45 = "6)o"
    var46 = module0.is_cloud(var45)
    assert var46 is False


def test_case_21():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = module0.is_cloud(var0)
    assert var2 is False
    var3 = "N"
    var4 = module0.is_cloud_v0(var3)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = module0.is_cloud_v0(var5)
    assert var7 is False
    var8 = "N"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = module0.is_cloud_v0(var10)
    assert var12 is False
    var13 = None
    var14 = module0.is_cloud_v0(var13)
    assert var14 is False
    var15 = "N"
    var16 = module0.is_cloud_v0(var15)
    assert var16 is False
    var17 = module0.is_cloud(var15)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud(var18)
    assert var19 is False
    var20 = module0.is_cloud(var18)
    assert var20 is False
    var21 = None
    var22 = module0.is_cloud(var21)
    assert var22 is False
    var23 = "3.5.136.0/22"
    var24 = module0.is_cloud_v0(var23)
    assert var24 is False
    var25 = None
    var26 = module0.is_cloud(var25)
    assert var26 is False
    var27 = "N"
    var28 = module0.is_cloud_v0(var27)
    assert var28 is False
    var29 = None
    var30 = module0.is_cloud(var29)
    assert var30 is False
    var31 = module0.is_cloud_v0(var29)
    assert var31 is False
    var32 = module0.is_cloud_v0(var29)
    assert var32 is False
    var33 = "N"
    var34 = module0.is_cloud_v0(var33)
    assert var34 is False
    var35 = "104.198.64.0/20"
    var36 = module0.is_cloud(var35)
    assert var36 is False
    var37 = None
    var38 = module0.is_cloud(var37)
    assert var38 is False
    var39 = "104.198.64.0/20"
    var40 = module0.is_cloud(var39)
    assert var40 is False
    var41 = "l3OZ\t2L4\t!"
    var42 = module0.is_cloud(var41)
    assert var42 is False
    var43 = "104.198.64.0/20"
    var44 = module0.is_cloud(var43)
    assert var44 is False
    var45 = "VD"
    var46 = module0.is_cloud_v0(var45)
    assert var46 is False


def test_case_22():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = module0.is_cloud_v0(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = "N"
    var8 = module0.is_cloud_v0(var7)
    assert var8 is False
    var9 = None
    var10 = module0.is_cloud(var9)
    assert var10 is False
    var11 = module0.is_cloud_v0(var9)
    assert var11 is False
    var12 = module0.is_cloud_v0(var9)
    assert var12 is False
    var13 = "x2luO}\\y/{DdT|Lh"
    var14 = module0.is_cloud_v0(var13)
    assert var14 is False


def test_case_23():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = module0.is_cloud_v0(var4)
    assert var6 is False
    var7 = module0.is_cloud_v0(var4)
    assert var7 is False
    var8 = "104.198.64.0/20"
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = "104.198.64.0/20"
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = None
    var13 = module0.is_cloud(var12)
    assert var13 is False
    var14 = "104.198.64.0/20"
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = "l3OZ\t2L4\t!"
    var17 = module0.is_cloud(var16)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud(var18)
    assert var19 is False
    var20 = "3.5.136.0/22"
    var21 = module0.is_cloud_v0(var20)
    assert var21 is False
    var22 = "N"
    var23 = module0.is_cloud_v0(var22)
    assert var23 is False
    var24 = "104.198.64.0/20"
    var25 = module0.is_cloud(var24)
    assert var25 is False
    var26 = None
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = "N"
    var29 = module0.is_cloud_v0(var28)
    assert var29 is False
    var30 = None
    var31 = module0.is_cloud(var30)
    assert var31 is False
    var32 = module0.is_cloud_v0(var30)
    assert var32 is False
    var33 = None
    var34 = module0.is_cloud_v0(var33)
    assert var34 is False
    var35 = "N"
    var36 = module0.is_cloud_v0(var35)
    assert var36 is False
    var37 = module0.is_cloud(var35)
    assert var37 is False
    var38 = None
    var39 = module0.is_cloud(var38)
    assert var39 is False
    var40 = module0.is_cloud(var38)
    assert var40 is False
    var41 = "35.206.192.0/18"
    var42 = module0.is_cloud_v0(var41)
    assert var42 is False


def test_case_24():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "N"
    var7 = module0.is_cloud_v0(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = module0.is_cloud_v0(var8)
    assert var10 is False
    var11 = module0.is_cloud_v0(var8)
    assert var11 is False
    var12 = "N"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = None
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = module0.is_cloud_v0(var14)
    assert var16 is False
    var17 = None
    var18 = module0.is_cloud_v0(var17)
    assert var18 is False
    var19 = "104.198.64.0/20"
    var20 = module0.is_cloud(var19)
    assert var20 is False
    var21 = None
    var22 = module0.is_cloud(var21)
    assert var22 is False
    var23 = "104.198.64.0/20"
    var24 = module0.is_cloud(var23)
    assert var24 is False
    var25 = "l3OZ\t2L4\t!"
    var26 = module0.is_cloud(var25)
    assert var26 is False
    var27 = "N"
    var28 = module0.is_cloud_v0(var27)
    assert var28 is False
    var29 = None
    var30 = module0.is_cloud(var29)
    assert var30 is False
    var31 = module0.is_cloud_v0(var29)
    assert var31 is False
    var32 = "104.198.64.0/20"
    var33 = module0.is_cloud(var32)
    assert var33 is False
    var34 = "N"
    var35 = module0.is_cloud_v0(var34)
    assert var35 is False
    var36 = module0.is_cloud(var34)
    assert var36 is False
    var37 = None
    var38 = module0.is_cloud(var37)
    assert var38 is False
    var39 = "3.5.136.0/22"
    var40 = module0.is_cloud_v0(var39)
    assert var40 is False
    var41 = None
    var42 = module0.is_cloud(var41)
    assert var42 is False
    var43 = "S|_1g{`:j[Nl#U6"
    var44 = module0.is_cloud(var43)
    assert var44 is False
    var45 = module0.is_cloud_v0(var27)
    assert var45 is False


def test_case_25():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = module0.is_cloud(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = module0.is_cloud(var5)
    assert var7 is False
    var8 = "N"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = module0.is_cloud(var8)
    assert var10 is False
    var11 = None
    var12 = module0.is_cloud(var11)
    assert var12 is False
    var13 = "N"
    var14 = module0.is_cloud_v0(var13)
    assert var14 is False
    var15 = None
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = module0.is_cloud_v0(var15)
    assert var17 is False
    var18 = module0.is_cloud_v0(var15)
    assert var18 is False
    var19 = "N"
    var20 = module0.is_cloud_v0(var19)
    assert var20 is False
    var21 = None
    var22 = module0.is_cloud(var21)
    assert var22 is False
    var23 = module0.is_cloud_v0(var21)
    assert var23 is False
    var24 = "N"
    var25 = module0.is_cloud_v0(var24)
    assert var25 is False
    var26 = None
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = module0.is_cloud_v0(var26)
    assert var28 is False
    var29 = None
    var30 = module0.is_cloud_v0(var29)
    assert var30 is False
    var31 = None
    var32 = module0.is_cloud(var31)
    assert var32 is False
    var33 = "3.5.136.0/22"
    var34 = module0.is_cloud_v0(var33)
    assert var34 is False
    var35 = "104.198.64.0/20"
    var36 = module0.is_cloud(var35)
    assert var36 is False
    var37 = None
    var38 = module0.is_cloud(var37)
    assert var38 is False
    var39 = "104.198.64.0/20"
    var40 = module0.is_cloud(var39)
    assert var40 is False
    var41 = None
    var42 = module0.is_cloud(var41)
    assert var42 is False


def test_case_26():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = module0.is_cloud(var0)
    assert var2 is False
    var3 = None
    var4 = module0.is_cloud(var3)
    assert var4 is False
    var5 = module0.is_cloud(var3)
    assert var5 is False
    var6 = "N"
    var7 = module0.is_cloud_v0(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = module0.is_cloud_v0(var8)
    assert var10 is False
    var11 = None
    var12 = module0.is_cloud_v0(var11)
    assert var12 is False
    var13 = "104.198.64.0/20"
    var14 = module0.is_cloud(var13)
    assert var14 is False
    var15 = "S|_1g{`:j[Nl#U6"
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = None
    var18 = module0.is_cloud(var17)
    assert var18 is False
    var19 = "3.5.136.0/22"
    var20 = module0.is_cloud_v0(var19)
    assert var20 is False
    var21 = "\r<t="
    var22 = module0.is_cloud(var21)
    assert var22 is False


def test_case_27():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "104.198.64.0/20"
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "104.198.64.0/20"
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = "l3OZ\t2L4\t!"
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = "N"
    var11 = module0.is_cloud_v0(var10)
    assert var11 is False
    var12 = "N"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = None
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = module0.is_cloud_v0(var14)
    assert var16 is False
    var17 = None
    var18 = module0.is_cloud_v0(var17)
    assert var18 is False
    var19 = module0.is_cloud_v0(var4)
    assert var19 is False


def test_case_28():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = module0.is_cloud(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = module0.is_cloud(var5)
    assert var7 is False
    var8 = "104.198.64.0/20"
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = "N"
    var11 = module0.is_cloud_v0(var10)
    assert var11 is False
    var12 = "104.198.64.0/20"
    var13 = module0.is_cloud(var12)
    assert var13 is False
    var14 = None
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = "N"
    var17 = module0.is_cloud_v0(var16)
    assert var17 is False
    var18 = module0.is_cloud(var16)
    assert var18 is False
    var19 = None
    var20 = module0.is_cloud(var19)
    assert var20 is False
    var21 = "3.5.136.0/22"
    var22 = module0.is_cloud_v0(var21)
    assert var22 is False
    var23 = "S|_1g{`:j[Nl#U6"
    var24 = module0.is_cloud(var23)
    assert var24 is False
    var25 = "104.198.64.0/20"
    var26 = module0.is_cloud(var25)
    assert var26 is False
    var27 = None
    var28 = module0.is_cloud(var27)
    assert var28 is False
    var29 = "104.198.64.0/20"
    var30 = module0.is_cloud(var29)
    assert var30 is False
    var31 = "l3OZ\t2L4\t!"
    var32 = module0.is_cloud(var31)
    assert var32 is False
    var33 = "99.77.133.0/24"
    var34 = module0.is_cloud_v0(var33)
    assert var34 is False


def test_case_29():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = module0.is_cloud_v0(var2)
    assert var4 is False
    var5 = "S|_1g{`:j[Nl#U6"
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = "N"
    var8 = module0.is_cloud_v0(var7)
    assert var8 is False
    var9 = "104.198.64.0/20"
    var10 = module0.is_cloud(var9)
    assert var10 is False
    var11 = None
    var12 = module0.is_cloud(var11)
    assert var12 is False
    var13 = "104.198.64.0/20"
    var14 = module0.is_cloud(var13)
    assert var14 is False
    var15 = "l3OZ\t2L4\t!"
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = "N"
    var18 = module0.is_cloud_v0(var17)
    assert var18 is False
    var19 = None
    var20 = module0.is_cloud(var19)
    assert var20 is False
    var21 = module0.is_cloud_v0(var19)
    assert var21 is False
    var22 = None
    var23 = module0.is_cloud_v0(var22)
    assert var23 is False
    var24 = "104.198.64.0/20"
    var25 = module0.is_cloud(var24)
    assert var25 is False
    var26 = None
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = "104.198.64.0/20"
    var29 = module0.is_cloud(var28)
    assert var29 is False
    var30 = None
    var31 = module0.is_cloud(var30)
    assert var31 is False
    var32 = "165.22.16.0/20"
    var33 = module0.is_cloud_v0(var32)
    assert var33 is False


def test_case_30():
    var0 = "ipv4Prefix"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False


def test_case_31():
    var0 = None
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = module0.is_cloud(var2)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = module0.is_cloud(var5)
    assert var7 is False
    var8 = "104.198.64.0/20"
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = "N"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = None
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = module0.is_cloud_v0(var14)
    assert var16 is False
    var17 = None
    var18 = module0.is_cloud_v0(var17)
    assert var18 is False
    var19 = "N"
    var20 = module0.is_cloud_v0(var19)
    assert var20 is False
    var21 = None
    var22 = module0.is_cloud(var21)
    assert var22 is False
    var23 = "N"
    var24 = module0.is_cloud_v0(var23)
    assert var24 is False
    var25 = None
    var26 = module0.is_cloud(var25)
    assert var26 is False
    var27 = module0.is_cloud_v0(var25)
    assert var27 is False
    var28 = module0.is_cloud_v0(var25)
    assert var28 is False
    var29 = "$"
    var30 = module0.is_cloud_v0(var29)
    assert var30 is False


def test_case_32():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "104.198.64.0/20"
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "l3OZ\t2L4\t!"
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = "N"
    var11 = module0.is_cloud_v0(var10)
    assert var11 is False
    var12 = None
    var13 = module0.is_cloud(var12)
    assert var13 is False
    var14 = module0.is_cloud_v0(var12)
    assert var14 is False
    var15 = module0.is_cloud_v0(var12)
    assert var15 is False
    var16 = "N"
    var17 = module0.is_cloud_v0(var16)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud(var18)
    assert var19 is False
    var20 = module0.is_cloud_v0(var18)
    assert var20 is False
    var21 = None
    var22 = module0.is_cloud(var21)
    assert var22 is False
    var23 = "3.5.136.0/22"
    var24 = module0.is_cloud_v0(var23)
    assert var24 is False
    var25 = "104.198.64.0/20"
    var26 = module0.is_cloud(var25)
    assert var26 is False
    var27 = None
    var28 = module0.is_cloud(var27)
    assert var28 is False
    var29 = "N"
    var30 = module0.is_cloud_v0(var29)
    assert var30 is False
    var31 = "N"
    var32 = module0.is_cloud_v0(var31)
    assert var32 is False
    var33 = module0.is_cloud(var31)
    assert var33 is False
    var34 = "ipv4Prefix"
    var35 = module0.is_cloud_v0(var34)
    assert var35 is False
    var36 = None
    var37 = module0.is_cloud(var36)
    assert var37 is False
    var38 = "T"
    var39 = module0.is_cloud(var38)
    assert var39 is False


def test_case_33():
    var0 = "ipv4Prefix"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = "104.198.64.0/20"
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "N"
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False
    var6 = None
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = module0.is_cloud_v0(var6)
    assert var8 is False
    var9 = None
    var10 = module0.is_cloud_v0(var9)
    assert var10 is False
    var11 = "9;z6cd+&7"
    var12 = module0.is_cloud(var11)
    assert var12 is False


def test_case_34():
    var0 = "ipv4Prefix"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "N"
    var7 = module0.is_cloud_v0(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = module0.is_cloud_v0(var8)
    assert var10 is False
    var11 = module0.is_cloud_v0(var8)
    assert var11 is False
    var12 = "104.198.64.0/20"
    var13 = module0.is_cloud(var12)
    assert var13 is False
    var14 = None
    var15 = module0.is_cloud(var14)
    assert var15 is False
    var16 = "104.198.64.0/20"
    var17 = module0.is_cloud(var16)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud(var18)
    assert var19 is False
    var20 = "104.198.64.0/20"
    var21 = module0.is_cloud(var20)
    assert var21 is False
    var22 = None
    var23 = module0.is_cloud(var22)
    assert var23 is False
    var24 = "104.198.64.0/20"
    var25 = module0.is_cloud(var24)
    assert var25 is False
    var26 = "l3OZ\t2L4\t!"
    var27 = module0.is_cloud(var26)
    assert var27 is False
    var28 = "N"
    var29 = module0.is_cloud_v0(var28)
    assert var29 is False
    var30 = module0.is_cloud(var28)
    assert var30 is False
    var31 = None
    var32 = module0.is_cloud(var31)
    assert var32 is False
    var33 = module0.is_cloud(var31)
    assert var33 is False
    var34 = None
    var35 = module0.is_cloud(var34)
    assert var35 is False
    var36 = "3.5.136.0/22"
    var37 = module0.is_cloud_v0(var36)
    assert var37 is False
    var38 = "N"
    var39 = module0.is_cloud_v0(var38)
    assert var39 is False
    var40 = None
    var41 = module0.is_cloud(var40)
    assert var41 is False
    var42 = module0.is_cloud_v0(var40)
    assert var42 is False
    var43 = 't9/X8u*m|"RZ\r*S1yL\x0b\x0b'
    var44 = module0.is_cloud(var43)
    assert var44 is False


def test_case_35():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = ""
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False


def test_case_36():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = module0.is_cloud(var0)
    assert var2 is False
    var3 = "N"
    var4 = module0.is_cloud_v0(var3)
    assert var4 is False
    var5 = None
    var6 = module0.is_cloud(var5)
    assert var6 is False
    var7 = module0.is_cloud_v0(var5)
    assert var7 is False
    var8 = module0.is_cloud_v0(var3)
    assert var8 is False


def test_case_37():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = "104.198.64.0/20"
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = None
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = "3.5.136.0/22"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = "ipv4Prefix"
    var11 = module0.is_cloud_v0(var10)
    assert var11 is False
    var12 = "N"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = module0.is_cloud(var12)
    assert var14 is False
    var15 = "N"
    var16 = module0.is_cloud_v0(var15)
    assert var16 is False
    var17 = None
    var18 = module0.is_cloud(var17)
    assert var18 is False
    var19 = module0.is_cloud_v0(var17)
    assert var19 is False
    var20 = module0.is_cloud_v0(var15)
    assert var20 is False
    var21 = "^DeM}V-)SXX:a:b_,i"
    var22 = module0.is_cloud(var21)
    assert var22 is False


def test_case_38():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = ""
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False
    var6 = "104.198.64.0/20"
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = "N"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = module0.is_cloud(var12)
    assert var14 is False
    var15 = "N"
    var16 = module0.is_cloud_v0(var15)
    assert var16 is False
    var17 = None
    var18 = module0.is_cloud(var17)
    assert var18 is False
    var19 = module0.is_cloud_v0(var17)
    assert var19 is False
    var20 = module0.is_cloud_v0(var15)
    assert var20 is False
    var21 = "N"
    var22 = module0.is_cloud_v0(var21)
    assert var22 is False
    var23 = module0.is_cloud(var21)
    assert var23 is False
    var24 = "N"
    var25 = module0.is_cloud_v0(var24)
    assert var25 is False
    var26 = "ipv4Prefix"
    var27 = module0.is_cloud_v0(var26)
    assert var27 is False
    var28 = "S|_1g{`:j[Nl#U6"
    var29 = module0.is_cloud(var28)
    assert var29 is False
    var30 = "N"
    var31 = module0.is_cloud_v0(var30)
    assert var31 is False
    var32 = module0.is_cloud(var30)
    assert var32 is False
    var33 = None
    var34 = module0.is_cloud(var33)
    assert var34 is False
    var35 = module0.is_cloud(var33)
    assert var35 is False
    var36 = module0.is_cloud_v0(var33)
    assert var36 is False


def test_case_39():
    var0 = "S|_1g{`:j[Nl#U6"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "N"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = module0.is_cloud_v0(var4)
    assert var6 is False
    var7 = None
    var8 = module0.is_cloud_v0(var7)
    assert var8 is False
    var9 = None
    var10 = module0.is_cloud(var9)
    assert var10 is False
    var11 = "Ud+na0+"
    var12 = module0.is_cloud_v0(var11)
    assert var12 is False


def test_case_40():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "N"
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False
    var6 = None
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = module0.is_cloud_v0(var6)
    assert var8 is False
    var9 = None
    var10 = module0.is_cloud_v0(var9)
    assert var10 is False
    var11 = "104.198.64.0/20"
    var12 = module0.is_cloud(var11)
    assert var12 is False
    var13 = None
    var14 = module0.is_cloud(var13)
    assert var14 is False
    var15 = ""
    var16 = module0.is_cloud_v0(var15)
    assert var16 is False
    var17 = "104.198.64.0/20"
    var18 = module0.is_cloud(var17)
    assert var18 is False
    var19 = None
    var20 = module0.is_cloud(var19)
    assert var20 is False
    var21 = "104.198.64.0/20"
    var22 = module0.is_cloud(var21)
    assert var22 is False
    var23 = "l3OZ\t2L4\t!"
    var24 = module0.is_cloud(var23)
    assert var24 is False
    var25 = "N"
    var26 = module0.is_cloud_v0(var25)
    assert var26 is False
    var27 = module0.is_cloud(var2)
    assert var27 is False


def test_case_41():
    var0 = "S|_1g{`:j[Nl#U6"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = "ipv4Prefix"
    var3 = module0.is_cloud_v0(var2)
    assert var3 is False
    var4 = None
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "3.5.136.0/22"
    var7 = module0.is_cloud_v0(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = "N"
    var11 = module0.is_cloud_v0(var10)
    assert var11 is False
    var12 = None
    var13 = module0.is_cloud(var12)
    assert var13 is False
    var14 = module0.is_cloud_v0(var12)
    assert var14 is False
    var15 = module0.is_cloud_v0(var12)
    assert var15 is False
    var16 = "104.198.64.0/20"
    var17 = module0.is_cloud(var16)
    assert var17 is False
    var18 = None
    var19 = module0.is_cloud(var18)
    assert var19 is False
    var20 = "N"
    var21 = module0.is_cloud_v0(var20)
    assert var21 is False
    var22 = module0.is_cloud(var20)
    assert var22 is False
    var23 = "N"
    var24 = module0.is_cloud_v0(var23)
    assert var24 is False
    var25 = None
    var26 = module0.is_cloud(var25)
    assert var26 is False
    var27 = module0.is_cloud_v0(var25)
    assert var27 is False
    var28 = module0.is_cloud_v0(var23)
    assert var28 is False
    var29 = "104.198.64.0/20"
    var30 = module0.is_cloud(var29)
    assert var30 is False
    var31 = "104.198.64.0/20"
    var32 = module0.is_cloud(var31)
    assert var32 is False
    var33 = None
    var34 = module0.is_cloud(var33)
    assert var34 is False
    var35 = ""
    var36 = module0.is_cloud_v0(var35)
    assert var36 is False
    var37 = "N"
    var38 = module0.is_cloud_v0(var37)
    assert var38 is False
    var39 = module0.is_cloud(var37)
    assert var39 is False
    var40 = None
    var41 = module0.is_cloud(var40)
    assert var41 is False
    var42 = module0.is_cloud(var40)
    assert var42 is False
    var43 = module0.is_cloud_v0(var6)
    assert var43 is False


def test_case_42():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = ""
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False
    var6 = "S|_1g{`:j[Nl#U6"
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = "ipv4Prefix"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = "N"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = module0.is_cloud(var12)
    assert var14 is False
    var15 = None
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = module0.is_cloud(var15)
    assert var17 is False
    var18 = module0.is_cloud_v0(var6)
    assert var18 is False


def test_case_43():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "N"
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False
    var6 = module0.is_cloud(var4)
    assert var6 is False
    var7 = None
    var8 = module0.is_cloud(var7)
    assert var8 is False
    var9 = module0.is_cloud(var7)
    assert var9 is False
    var10 = "N"
    var11 = module0.is_cloud_v0(var10)
    assert var11 is False
    var12 = module0.is_cloud(var10)
    assert var12 is False
    var13 = "N"
    var14 = module0.is_cloud_v0(var13)
    assert var14 is False
    var15 = None
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = module0.is_cloud_v0(var15)
    assert var17 is False
    var18 = module0.is_cloud_v0(var13)
    assert var18 is False
    var19 = "dyi|lax`z7Qy"
    var20 = module0.is_cloud_v0(var19)
    assert var20 is False


def test_case_44():
    var0 = "N"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = module0.is_cloud(var0)
    assert var2 is False
    var3 = "S|_1g{`:j[Nl#U6"
    var4 = module0.is_cloud(var3)
    assert var4 is False
    var5 = "N"
    var6 = module0.is_cloud_v0(var5)
    assert var6 is False
    var7 = "104.198.64.0/20"
    var8 = module0.is_cloud(var7)
    assert var8 is False
    var9 = "104.198.64.0/20"
    var10 = module0.is_cloud(var9)
    assert var10 is False
    var11 = None
    var12 = module0.is_cloud(var11)
    assert var12 is False
    var13 = "104.198.64.0/20"
    var14 = module0.is_cloud(var13)
    assert var14 is False
    var15 = "l3OZ\t2L4\t!"
    var16 = module0.is_cloud(var15)
    assert var16 is False
    var17 = module0.is_cloud(var0)
    assert var17 is False


def test_case_45():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = ""
    var5 = module0.is_cloud_v0(var4)
    assert var5 is False
    var6 = "104.198.64.0/20"
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = None
    var9 = module0.is_cloud(var8)
    assert var9 is False
    var10 = None
    var11 = module0.is_cloud(var10)
    assert var11 is False
    var12 = "3.5.136.0/22"
    var13 = module0.is_cloud_v0(var12)
    assert var13 is False
    var14 = "N"
    var15 = module0.is_cloud_v0(var14)
    assert var15 is False
    var16 = module0.is_cloud(var14)
    assert var16 is False
    var17 = "N"
    var18 = module0.is_cloud_v0(var17)
    assert var18 is False
    var19 = None
    var20 = module0.is_cloud(var19)
    assert var20 is False
    var21 = "N"
    var22 = module0.is_cloud_v0(var21)
    assert var22 is False
    var23 = None
    var24 = module0.is_cloud(var23)
    assert var24 is False
    var25 = module0.is_cloud_v0(var23)
    assert var25 is False
    var26 = module0.is_cloud_v0(var23)
    assert var26 is False
    var27 = "N"
    var28 = module0.is_cloud_v0(var27)
    assert var28 is False
    var29 = module0.is_cloud(var27)
    assert var29 is False
    var30 = None
    var31 = module0.is_cloud(var30)
    assert var31 is False
    var32 = module0.is_cloud(var30)
    assert var32 is False
    var33 = "N"
    var34 = module0.is_cloud_v0(var33)
    assert var34 is False
    var35 = None
    var36 = module0.is_cloud(var35)
    assert var36 is False
    var37 = module0.is_cloud_v0(var35)
    assert var37 is False
    var38 = None
    var39 = module0.is_cloud_v0(var38)
    assert var39 is False
    var40 = "N"
    var41 = module0.is_cloud_v0(var40)
    assert var41 is False
    var42 = None
    var43 = module0.is_cloud(var42)
    assert var43 is False
    var44 = module0.is_cloud_v0(var42)
    assert var44 is False
    var45 = "S|_1g{`:j[Nl#U6"
    var46 = module0.is_cloud(var45)
    assert var46 is False
    var47 = "dz\x0b~O5MpvH}WbrwE9%e\n"
    var48 = module0.is_cloud_v0(var47)
    assert var48 is False


def test_case_46():
    var0 = "ipv4Prefix"
    var1 = module0.is_cloud_v0(var0)
    assert var1 is False
    var2 = "S|_1g{`:j[Nl#U6"
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = module0.is_cloud(var2)
    assert var4 is False


def test_case_47():
    var0 = "104.198.64.0/20"
    var1 = module0.is_cloud(var0)
    assert var1 is False
    var2 = None
    var3 = module0.is_cloud(var2)
    assert var3 is False
    var4 = "104.198.64.0/20"
    var5 = module0.is_cloud(var4)
    assert var5 is False
    var6 = "l3OZ\t2L4\t!"
    var7 = module0.is_cloud(var6)
    assert var7 is False
    var8 = "N"
    var9 = module0.is_cloud_v0(var8)
    assert var9 is False
    var10 = module0.is_cloud(var8)
    assert var10 is False
    var11 = "N"
    var12 = module0.is_cloud_v0(var11)
    assert var12 is False
    var13 = None
    var14 = module0.is_cloud(var13)
    assert var14 is False
    var15 = module0.is_cloud_v0(var13)
    assert var15 is False
    var16 = module0.is_cloud_v0(var11)
    assert var16 is False
    var17 = "N"
    var18 = module0.is_cloud_v0(var17)
    assert var18 is False
    var19 = None
    var20 = module0.is_cloud(var19)
    assert var20 is False
    var21 = module0.is_cloud_v0(var19)
    assert var21 is False
    var22 = None
    var23 = module0.is_cloud_v0(var22)
    assert var23 is False
    var24 = "D"
    var25 = module0.is_cloud_v0(var24)
    assert var25 is False
